```groovy
buildscript {
    ext {
        expoVersion = "52.0.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath('com.android.tools.build:gradle:8.1.0')
        classpath('com.google.gms:google-services:4.3.15') // Google Services classpath ekleniyor
        // ... diğer classpath bağımlılıkları
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
```